### PR TITLE
Expand Program Change messages across banks

### PR DESCRIPTION
**Pull request by diyelectromusic**
I've added an option to allow Program Change 0..127 to "stripe" across four consecutive banks, starting with the selected bank. This allows a simple configuration of just four banks to have all 128 voices available over PC messages without requiring an actual bank select message.  This does not affect the bank select mechanism though.

I couldn't think of a downside of this being enabled, so I enabled it by default.  But it is a config option regardless.

This was discussed a little in Issue #391 

Kevin

### CODE REVIEW

**Comment by diyelectromusic** [comment]
Yes will do. If accepted I can update the wiki when ready

**Comment by probonopd** [comment]
This branch has conflicts that must be resolved. I kinda feared this would happen...

**Comment by diyelectromusic** [comment]
Yeah - I thought each was building on each other.  I just don't "get" git :)

The conflicts I think are minimal.  Is that something I have to resolve or something you do as part of a merge?

**Comment by probonopd** [comment]
Would be tremendous if you could resolve the conflicts. Thank you so much!

In general, it's best to get one PR merged (all changes you make in your branch that went into the PR get automatically amended to the PR), and once that is merged, start another PR. As soon as there are multiple PRs open at the same time, there is always the chance of conflicts in case both PRs edit the same file(s) in similar places.

**Comment by diyelectromusic** [comment]
Right, looks like both of these have their conflicts resolved... although accepting one may well produce more in the other!  Doesn't really matter though - I'll take another look then.

BTW if there was an order, I'd say accept #463 first.

Kevin

**Comment by probonopd** [comment]
> BTW if there was an order, I'd say accept https://github.com/probonopd/MiniDexed/pull/463 first.

Done :-)

**Comment by diyelectromusic** [comment]
Documentation for this and #459 now added to the wiki.

Keivn

**Comment by probonopd** [comment]
Thanks Kevin, that's very helpful.

**Comment by diyelectromusic** [comment]
If there are no objections, can we merge this one in? :)

Thanks,
Kevin

**Comment by Banana71** [comment]
@diyelectromusic, 
is this the door opener to play GM midi files?  Then we should create a GM bank here (4 banks).  This enables completely new applications.  With two miniDexed you could then play any GeneralMidi®️ file 🎉🧚🏽

**Comment by diyelectromusic** [comment]
> @diyelectromusic, is this the door opener to play GM midi files? Then we should create a GM bank here (4 banks). This enables completely new applications. With two miniDexed you could then play any GeneralMidi®️ file 🎉🧚🏽

Well kind of maybe... ish... not sure.  The main problem is that GM files tend to send a lot of additional data over for standardised controllers and things that I doubt the MiniDexed would support or recognise. It might even map them onto something else which always causes entertaining results.  Also they tend to have a lot more than 8 tracks on the go.  And as you say, no drums :)

But it would certainly be possible to have a "GM equivalent" instrument list across four banks, yes.

That isn't to say you can't send MIDI files through.  I still think my [80s DX7 style "Jupiter" from Holst's Planets](https://www.youtube.com/watch?v=E5cnrfKYE4M) was quite credible on MiniDexed, but I find that these older systems need the MIDI files to be pretty "clean" to sound any good :)

Kevin

**Comment by diyelectromusic** [comment]
Mind you, I'm now wondering about a cheap [VS1053/VS1003 module](https://diyelectromusic.wordpress.com/2022/09/11/arduino-vs1053-general-midi-synth/) on a Pi IO board that could do the GM drums for a MiniDexed FM GM module... or maybe I should stay OPL and add a [YM2413](https://diyelectromusic.wordpress.com/2023/01/27/arduino-opl-fm-synth/)...

**Comment by probonopd** [comment]
And don't forget the https://github.com/dwhinham/mt32-pi, which is built on Circle just like MiniDexed.

**Comment by diyelectromusic** [comment]
> And don't forget the https://github.com/dwhinham/mt32-pi, which is built on Circle just like MiniDexed.

I've got a few of those too (and a real MT-32 as it happens) :)

Kevin

**Comment by diyelectromusic** [comment]
> If there are no objections, can we merge this one in? :)

Hi @probonopd is there an issue with this one?  Just thinking if it isn't going to be merged in I probably should take the setting off the Wiki :)

Kevin

**Comment by probonopd** [comment]
Thanks @diyelectromusic.
Could we add a sentence to the documentation explaining what this is useful for?

**Comment by diyelectromusic** [comment]
> Could we add a sentence to the documentation explaining what this is useful for?

I already added this to the wiki describing the setting - is that what you mean or do you want something else (if so where)?

Kevin

**Comment by diyelectromusic** [comment]
On the one hand it mirrors the voice selection pattern of a DX7II (apparently) as described in the linked issue; on the other it allows more voices to be chosen from just using Program Change messages without having to have knowledge of how voices/banks mix together; if only four banks were installed then all voices could be chosen from a more modern keyboard with 128 voices; also, as was stated above, it could allow someone to build up a General MIDI style set of voices; it also makes it easier for a "universal" (i.e. non-DX7 specific) DIY program changer to select one of 128 voices...

There are many possible use-cases, but ultimately it is just another option for people to use if they wish.  I'm sure people will find all sorts of use cases should they wish to - I don't think we need to be prescriptive in the documentation.  If they need convincing to use it, they probably don't need it.  But if they've played with voice selection from other MIDI devices (rather than a DAW that has been configured for DX7s) it might prove quite useful.

Kevin

**Pull request merged**
