### PR TITLE
Lower debounce time

### PR DESCRIPTION
**Pull request by probonopd**
https://github.com/probonopd/MiniDexed/issues/713

### CODE REVIEW

**Comment by miotislucifugis** [comment]
Wow, Thanks!   This seems to be working great.  Even the fastest taps get registered.     However, Im finding that if i do a couple of fast successive taps, like 3 quick ones in a row to go back 3 steps,  only only one press gets identified....but I guess that this is a limit of the double tap timeout.

**Comment by probonopd** [comment]
@diyelectromusic agree to merge this? See @miotislucifugis last comment in https://github.com/probonopd/MiniDexed/issues/713.

At this time, I'd rather not touch `BUTTONS_UPDATE_NUM_TICKS` because it might impact overall performance.

**Comment by diyelectromusic** [comment]
It's a little hard to say really, but yes, that last comment is encouraging.

I do think we should wait until someone tests this with other buttons though.  We can't be sure we haven't introduced a debouncing issue with slower/noisier buttons, so I think others ought to give it a bit of a test first.

If I get a chance, I'll load it up onto my various builds and see what it does, but that probably won't be for a few days and all my builds include capacitors for some hardware debouncing so might not be representative anyway.

It would be nice to have some proper profiling of the timers/responses involved in buttons and their scanning to put some sense to those numbers, but that would need an instrumented (e.g. with oscilloscope/GPIO outputs) build to be tested which would take a fair bit of time, so I guess we just go with the "is anyone shouting this is broken" approach for now :)

Kevin

**Comment by miotislucifugis** [comment]
I can test that tomorrow.  My switches are on a daughter board and I have an other board that I can swap in that has the standard little pcb push buttons.   For what its worth, I currently see no issue w/ the encoder switch.

**Comment by miotislucifugis** [comment]
Regular switches appear to be working fine in this build... at least for me

**Comment by probonopd** [comment]
Merging. Please comment here if you experience any button related issues.
Thanks!

**Pull request merged**
