### PR TITLE
Next try for ReverbMixer and NEON extensions (RPi2/3/4)

### PR DESCRIPTION
**Pull request by dcoredump**
I think now the CI pipeline should get green.

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @dcoredump. The build is succeeding now. (By the way, you wouldn't have had to open a new PR. As you can see, as soon as you pushed your commit "Fix for building for RPi1" to your branch from which you had created the original PR, a new build was triggered in the original PR automatically, which succeeded. Just as an info to save you some extra work next time.)

The menu item appears but does not behave entirely correctly:

image

Turning the knob counter-clockwise (as indicated by the `<` arrow) does nothing.
I would assume it should go down to 98, 97,... 0?

Turning the knob clockwise results in:

image

at which point the knob does not react anymore at all.

@rsta maybe you can spot the bug in the menu-related code easily?

**Comment by dcoredump** [comment]
Sorry @probonopd  @rsta2 but I have programmed this "blind" without having a display.

**Comment by probonopd** [comment]
Congrats that you came that far without an ability to test!

**Comment by rsta2** [comment]
There must be a line to `CUIMenu::s_TGParameter[]` added with minimum, maximum and step width of the `TGParameterReverbSend` [here](https://github.com/probonopd/MiniDexed/blob/2091e63bf2f876eb5e54af01f4cccbe3d3577244/src/uimenu.cpp#L183).

**Comment by probonopd** [comment]
Getting

```
uimenu.cpp:183:1: error: too many initializers for 'const CUIMenu::TParameter [6]'
  183 | };
      | ^
make: *** [../circle-stdlib/libs/circle/Rules.mk:144: uimenu.o] Error 1
```

Did I do it wrong?

**Comment by rsta2** [comment]
You have to apply the PR, that's all.

**Comment by probonopd** [comment]
D'oh! I had edited in the wrong repo. Fingers crossed that this build will work.

**Comment by probonopd** [comment]
That didn't work either...

```
  CPP   ../Synth_Dexed/src/sin.o
  CC    ../CMSIS_5/CMSIS/DSP/Source/SupportFunctions/SupportFunctions.o
  CC    ../CMSIS_5/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.o
  CC    ../CMSIS_5/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctions.o
  CC    ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o
  CC    ../CMSIS_5/CMSIS/DSP/Source/CommonTables/CommonTables.o
  CC    ../CMSIS_5/CMSIS/DSP/ComputeLibrary/Source/arm_cl_tables.o
uimenu.cpp:174:27: error: redefinition of 'const CUIMenu::TParameter CUIMenu::s_TGParameter [7]'
  174 | const CUIMenu::TParameter CUIMenu::s_TGParameter[CMiniDexed::TGParameterUnknown] =
      |                           ^~~~~~~
uimenu.cpp:162:27: note: 'const CUIMenu::TParameter CUIMenu::s_TGParameter [7]' previously defined here
  162 | const CUIMenu::TParameter CUIMenu::s_TGParameter[CMiniDexed::TGParameterUnknown] =
      |                           ^~~~~~~
In file included from ../circle-stdlib/libs/circle/include/circle/exceptionstub.h:23,
                 from ../circle-stdlib/libs/circle/include/circle/interrupt.h:24,
                 from ../circle-stdlib/libs/circle/include/circle/timer.h:23,
                 from uimenu.h:27,
                 from uimenu.cpp:23:
uimenu.cpp: In static member function 'static std::string CUIMenu::GetGlobalValueString(unsigned int, int)':
uimenu.cpp:684:23: error: invalid application of 'sizeof' to incomplete type 'const CUIMenu::TParameter []'
  684 |  assert (nParameter < sizeof CUIMenu::s_GlobalParameter / sizeof CUIMenu::s_GlobalParameter[0]);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../circle-stdlib/libs/circle/include/circle/macros.h:31:42: note: in definition of macro 'likely'
   31 | #define likely(exp) __builtin_expect (!!(exp), 1)
      |                                          ^~~
uimenu.cpp:684:2: note: in expansion of macro 'assert'
  684 |  assert (nParameter < sizeof CUIMenu::s_GlobalParameter / sizeof CUIMenu::s_GlobalParameter[0]);
      |  ^~~~~~
make: *** [../circle-stdlib/libs/circle/Rules.mk:144: uimenu.o] Error 1
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

**Comment by probonopd** [comment]
Now the menu behavior is fixed. @rsta2 woud you like to review the code prior to merging?

**Comment by rsta2** [comment]
I can do this tomorrow.

**Comment by rsta2** [comment]
While looking at the modifications to the code I found the following:

* In `SetPan()` in minidexed.cpp: I think the input range to `mapfloat()` is wrong (-99,99), must be (0,127).
* In `SetMasterTune()` and `SetParameter()` in minidexed.cpp: The `constrain()` macros do not have an effect. The resulting value must be assigned to the input variable again.
* In `Save()` in performanceconfig.cpp: The "ReverbSend#" parameters must be set in the TG loop, to be saved to the *performance.ini* file, like that:

```
PropertyName.Format ("ReverbSend%u", nTG+1);
m_Properties.SetNumber (PropertyName, m_nReverbSend[[nTG]);
```

* In `ProcessSound()` in minidexed.cpp: The variant for the RPi 1 (without `ARM_ALLOW_MULTI_CORE` defined) produces Stereo sound data, but the sound driver is initialized for Mono there.

Not a serious problem, but perhaps for later:

* Should use `new` and `delete` instead `malloc()` and `free()` in a C++ program, even for allocating arrays of simple data types:

```
float32_t* tmp = new float32_t[buffer_length];
delete [] tmp;		// the [] only, if new was used for an array

instead of

float32_t* tmp=(float32_t*)malloc(sizeof(float32_t)*buffer_length);
free(tmp);
```

* If I understand this right, `doAddMix()` allocates a temporary buffer using `malloc()` at each time, when it is called, which is often. Perhaps this could be optimized by placing the data on the stack in a local variable. `malloc()` (and `new`) consume some processing time to execute.
* Log messages (`LOGERR()`) do not need a trailing "\n", it is automatically appended.

**Comment by rsta2** [comment]
In case it helps to apply this great improvement PR to the audio pipeline, attached here are the small patches for the little things, that I've noted in my previous comment. *patch1.patch* contains the modifications to *minidexed.cpp* and *performanceconfig.cpp* and *patch2.patch* the not serious patches to *effect_mixer.hpp* and *effect_compressor.cpp*. I tested to build this on RPi 1-4, but run it on RPi 3 only.

[patches.zip](https://github.com/probonopd/MiniDexed/files/8488817/patches.zip)

**Comment by probonopd** [comment]
Tested on RPi Zero, 2, 4.
Thanks @dcoredump and @rsta2!

**Comment by rsta2** [comment]
At the moment MiniDexed will be built with -O2 optimization. @dcoredump Can it be, that we need -O3 for the NEON optimizations to take effect? This could be enabled with:

```
diff --git a/src/Makefile b/src/Makefile
index e967049..3ea9c78 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -11,5 +11,7 @@ OBJS = main.o kernel.o minidexed.o config.o userinterface.o uimenu.o \
        sysexfileloader.o performanceconfig.o perftimer.o \
        effect_compressor.o effect_platervbstereo.o
 
+OPTIMIZE = -O3
+
 include ./Synth_Dexed.mk
 include ./Rules.mk
```

**Comment by dcoredump** [comment]
> Can it be, that we need -O3 for the NEON optimizations to take effect?


I am not sure if this is needed. Do we get problems when enabling `-O3` always?

**Comment by rsta2** [comment]
I think `-O3` can be generally enabled for the MiniDexed *src/* folder. This includes the *Synth_Dexed* and *CMSIS* sources. I do not expect problems there.

**Pull request merged**
