### PR TITLE
Initial support for I2C HD44780 displays

### PR DESCRIPTION
**Pull request by probonopd**
Initial support for I2C HD44780 displays, closes https://github.com/probonopd/MiniDexed/issues/169

Thanks @diyelectromusic

### CODE REVIEW

**Comment by probonopd** [comment]
Ready for testing: [MiniDexed_2022-05-15-d68a458](https://github.com/probonopd/MiniDexed/suites/6510798458/artifacts/242193362)

__Please note:__ You need to set `LCDI2CAddress=27` in `minidexed.ini` for i2c to be used for the display.

**Comment by diyelectromusic** [comment]
> Works great for me! 👍

Brilliant! I'll give your update a try later :)

**Comment by luisfcorreia** [comment]
Is there a build I can test?

(got compile errors in main branch)

**Comment by probonopd** [comment]
> (got compile errors in main branch)

Did you do this?

```
# Get develop branch of circle
cd circle-stdlib/libs/circle
git checkout ae22928 # develop
cd -
```

**Comment by luisfcorreia** [comment]
yes, it now compiles without issues but LCD still isn't working

(and I ran out of time to investigate further)

**Comment by probonopd** [comment]
Do the latest builds from the GitHub Releases page still work for you? They have the i2c code as well. Are you trying to use your display with i2c? Did you put `LCDI2CAddress=0x27` into `minidexed.ini`? Can you verify that your display is using that address?

**Comment by luisfcorreia** [comment]
LCDI2CAddress is added, just verified teh address was validated with Raspbian just now

still no dice, will review connections in a bit

**Comment by probonopd** [comment]
Contrast set properly? This got me more than once...

**Pull request merged**
