### PR TITLE
Patch in WM8960 support

### PR DESCRIPTION
**Pull request by probonopd**
Temporary patch to add WM8960 support until https://github.com/rsta2/circle/pull/286 is integrated into Circle

Thanks @matemaciek

### CODE REVIEW

**Comment by probonopd** [comment]
Tested with MiniDexed and a WM8960 DAC, works for me! Both the headphone jack on the WM8960 board and also the speakers connected to the built in amplifier +1

Here is the build:
https://github.com/probonopd/MiniDexed/suites/6210021520/artifacts/219385493

Now it would be good if someone with a PCM5102A or PCM5122 based DAC could also test this in order to ensure that it doesn't break those.

**Comment by probonopd** [comment]
@matemaciek I am mirroring and locally applying your patch in MiniDexed for now so that we can enjoy our WM8960s while an architecturally cleaner solution is being worked out in Circle.

**Comment by ChKK1963** [comment]
> It would be good if someone with access to a PCM5122 DAC could test the build from this branch (linked above) to ensure this doesn't break the PCM5122 which also uses i2c

Just tested the build with my new Raspiaudio+ V2 DAC which has a PCM5102A DAC. Seems to work fine.

**Comment by probonopd** [comment]
Thanks for testing @ChKK1963. We still need to find someone with a PCM5122 DAC though, as that one has i2c while the PCM5102A doesn't.

**Comment by matemaciek** [comment]
> Also, since this is auto-detecting i2c addresses, should we remove the related code from MiniDexed?
Is there any? I only see passing of optional I2C address, and it still makes sense - if user provides specific address, auto-detecting is skipped.

**Comment by rsta2** [comment]
I tried a PiFi DAC+ v2.0 HAT (uses a PCM5122 DAC) attached to a RPi Zero 2 W using this build:

https://github.com/probonopd/MiniDexed/suites/6210021520/artifacts/219385493

First it initialized OK, but after some seconds the sound was strange and after a restart, the I2C initialization failed (-2 from all probed addresses). I aborted the test, because I don't want to destroy something.

With a kernel image, built from the *main* branch, everything works OK.

**Comment by matemaciek** [comment]
I've ordered PiFi, I'll look into it. Previous version was just assuming PCM5122 is present and was blindly sending its init sequence on its two known addresses. Can you try setting `DACI2CAddress=76` and if that doesn't work `DACI2CAddress=77` in `minidexed.ini`?

**Comment by rsta2** [comment]
@matemaciek I guess the *i2cdetect* test, you have implemented, does not work reliable with some devices. I will wait for the license information and then merge your PR, maybe with some modifications. Then I will test again.

**Comment by matemaciek** [comment]
@rsta2 They've just added GPLv3 (-:

**Comment by probonopd** [comment]
WM8960 works. If PCM5xxx also still works, we might want to consider merging.

**Comment by probonopd** [comment]
PCM5xxx confirmed, hence merging.

**Pull request merged**
