### PR TITLE
uimenu: Add "Save > Performance" function

### PR DESCRIPTION
**Pull request by rsta2**
* Saves the performance config to performance.ini
* Comments in an existing file will be overwritten (!!!)
* Function displays "Completed" and returns to "Save" menu

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @rsta2. Can you have a look at the confliciting files please?

**Comment by rsta2** [comment]
Done.

**Comment by probonopd** [comment]
...and tested successfully :+1:

**Comment by probonopd** [comment]
Documentation updated.

**Comment by probonopd** [comment]
Just an idea, could https://github.com/benhoyt/inih allow us to preserve comments when saving?https://github.com/dwhinham/mt32-pi is using it.

**Comment by rsta2** [comment]
Probably possible, but won't be done by myself. See #89.

**Pull request merged**
