### PR TITLE
Enable filter in Synth_Dexed, UI and performance.ini

### PR DESCRIPTION
**Pull request by rsta2**
@dcoredump Requires the following patch in Synth_Dexed for successful build:

```
diff --git a/src/PluginFx.cpp b/src/PluginFx.cpp
index 9e850e1..4e40731 100644
--- a/src/PluginFx.cpp
+++ b/src/PluginFx.cpp
@@ -48,11 +48,11 @@ inline static float tptlpupw(float & state , float inp , float cutoff , float sr
 //    return (param) * (max - min) + min;
 //}
 
-/*
+#ifdef USE_FX
 static float logsc(float param, const float min, const float max, const float rolloff = 19.0f) {
   return ((EXP_FUNC(param * LOG_FUNC(rolloff + 1)) - 1.0f) / (rolloff)) * (max - min) + min;
 }
-*/
+#endif
 
 PluginFx::PluginFx() {
   Cutoff = 1.0;
```

### CODE REVIEW

**Comment by dcoredump** [comment]
Added patch. Many thanks @rsta2!!!

**Comment by probonopd** [comment]
Some day I need to learn how to update a git submodule in a PR without merging the PR...

Something like this?

```
git clone https://github.com/probonopd/MiniDexed
git pull origin pull/93/head # PR #93
cd MiniDexed
git submodule update --init --recursive
cd Synth_Dexed
git pull origin master
git add -A
git commit
git push
```

**Comment by probonopd** [comment]
Continues in #94

**Comment by rsta2** [comment]
```
cd Synth_Dexed
git fetch
git checkout abcdef      # some hash
cd ..
git add Synth_Dexed
git commit -m "Submodule updated"
git push
```

**Comment by probonopd** [comment]
Adding to the documentation. Thanks @rsta2

**Comment by probonopd** [comment]
Actually this doesn't push the changes to the PR... one probably needs to push to the branch from which the PR was created.

**Comment by probonopd** [comment]
...which I can't do either:

```
git clone https://github.com/rsta2/MiniDexed/
cd MiniDexed
git checkout enable-filter
git submodule update --init --recursive
cd Synth_Dexed\ngit fetch
git checkout c58ac7c2894573b566a711cbccd781db22780ea2
cd ..
git add Synth_Dexed
git commit -m "Submodule updated"
git push

 ! [remote rejected] enable-filter -> enable-filter (permission denied)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/rsta2/MiniDexed/'
```

**Comment by rsta2** [comment]
Possibly you have to explicitly specify the branch to push to:

```
git push origin enable-filter
```

**Comment by probonopd** [comment]
Most likely. Will try it the next time! Thanks.

**Pull request merged**
