### PR TITLE
Support more MIDI CCs

### PR DESCRIPTION
**Pull request by probonopd**
Add support for MIDI CCs

- 10 = Pan
- 71 = Resonance
- 74 = Frequency Cutoff
- 91 = Reverb Send
- 94 = Detune Level

Closes https://github.com/probonopd/MiniDexed/issues/121

### CODE REVIEW

**Comment by probonopd** [comment]
I think I was able to implement them except for 91 = Reverb Level, because there is no `m_pSynthesizer->SetReverbLevel` like for the other parameters. Probably we have to implement it in `minidexed.cpp`. Since this is a global (non-TG) parameter I was not sure how to do this.

**Comment by rsta2** [comment]
Regarding 91 (Reverb Level) I'm honestly not sure. Perhaps it's better to use `TGParameterReverbSend` instead, because it is local to the TG, and let Reverb Level only be modified from the UI. You can change `TGParameterReverbSend` from *mididevice.cpp* like that:

```
m_pSynthesizer->SetTGParameter (CMiniDexed::TGParameterReverbSend, nValue,  nTG);
```

Some parameters are not in the MIDI range 0..127. They must be mapped to that range.

**Comment by probonopd** [comment]
> Perhaps it's better to use TGParameterReverbSend instead, because it is local to the TG

Yes, it'd be more consistent with the other params indeed.

> Some parameters are not in the MIDI range 0..127. They must be mapped to that range.

https://github.com/probonopd/MiniDexed/blob/43d1b3ab939213ea49e7b19cb6d35ad6ca9eb09a/src/minidexed.cpp#L386

should take care of that, right?

**Comment by rsta2** [comment]
`constrain()` only checks, if the parameter is in the given range, but does not map it. To map from one range (MIDI) to another use:

```
nReverbSend = (unsigned) maplong ((long) nReverbSend, 0, 127, 0, 99);
```

**Comment by probonopd** [comment]
10 = Pan: **0-127**
71 = Resonance: **0-99**
74 = Frequency Cutoff: **0-99**
91 = Reverb Send: **0-99**
94 = Detune Level: **-99-99**

**Pull request merged**
