### PR TITLE
ReverbSend and internal mixers

### PR DESCRIPTION
**Pull request by dcoredump**
Now we have a mixer object (thanks for helping @rsta!). All TGs are now mixed with this mixer object, which is also responsible for the panning. Also an amount of each TG signal is send to the global reverb via a mixer object (also respecting the panorama of the TG).

I also added a menu entry, but currently I had no time to attach my LCD and the encoder to my Raspi - therefore I could not test it. But I can confirm that MiniDexed is running with a HifiBerry audio card!

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @dcoredump. Do you have any idea why we are getting `make[1]: aarch64-none-elf-g++: Command not found` all of a sudden?

**Comment by dcoredump** [comment]
No, for me RPi3 and 4 are Wirkung.

**Comment by dcoredump** [comment]
> No, sorry. For me RPi3 and 4 are working.

**Comment by probonopd** [comment]
It's RPi2 that is failing.

**Comment by dcoredump** [comment]
> It's RPi2 that is failing. Why is it looking for aarch64 in the first place?

I havn't changed anything. Just before the PR I rebased my fork... Perhaps that wad the problem?

**Comment by probonopd** [comment]
Coud it have to do with a leftover [src/minidexed.cpp.O](https://github.com/probonopd/MiniDexed/pull/85/files#diff-a4ed1aef8d642a1e45fb8e506286a30c45de08139fe80ffb1e194237452f168d)? Can it be removed?

**Comment by probonopd** [comment]
I'd be surprised if that caused it because main in still building. I am puzzled. Are you drawing in any new dependencies for which we might need an additional "make clean" step when we build for 32 bit following successful 64 bit builds?

**Comment by rsta2** [comment]
I think the problem is, that the file *fm_op_kernel.cpp* in Synth_Dexed does not build for 32-bit. There are many implicit type conversions, which do not work. They must be casted explicitly. @dcoredump can you try to build this locally for the RPi 2 (`RPI=2 build.sh`)? You will get many errors, which must be solved. Currently it does build for 64-bit only.

**Comment by dcoredump** [comment]
I think the problems are due to the NEON optimizations I added yesterday. They can be disabled by removing `-DHAVE_NEON` from Dexed_Synth.mk.

**Comment by rsta2** [comment]
OK, then this option must be applied for AArch64 only. This patch does it:

```
diff --git a/src/Synth_Dexed.mk b/src/Synth_Dexed.mk
index 20d6218..67d31b4 100644
--- a/src/Synth_Dexed.mk
+++ b/src/Synth_Dexed.mk
@@ -34,6 +34,10 @@ INCLUDE += -I $(CMSIS_CORE_INCLUDE_DIR)
 INCLUDE += -I $(CMSIS_DSP_INCLUDE_DIR)
 INCLUDE += -I $(CMSIS_DSP_PRIVATE_INCLUDE_DIR)
 INCLUDE += -I $(CMSIS_DSP_COMPUTELIB_INCLUDE_DIR)
-DEFINE += -DARM_MATH_NEON -DHAVE_NEON
+
+DEFINE += -DARM_MATH_NEON
+ifeq ($(strip $(AARCH)),64)
+DEFINE += -DHAVE_NEON
+endif
 
 EXTRACLEAN = $(SYNTH_DEXED_DIR)/*.[od] $(CMSIS_DSP_SOURCE_DIR)/SupportFunctions/*.[od] $(CMSIS_DSP_SOURCE_DIR)/SupportFunctions/*.[od] $(CMSIS_DSP_SOURCE_DIR)/BasicMathFunctions/*.[od] $(CMSIS_DSP_SOURCE_DIR)/FastMathFunctions/*.[od] $(CMSIS_DSP_SOURCE_DIR)/FilteringFunctions/*.[od] $(CMSIS_DSP_SOURCE_DIR)/CommonTables/*.[od] $(CMSIS_DSP_COMPUTELIB_SRC_DIR)/*.[od]
```

**Comment by rsta2** [comment]
Yes, with this patch, everything should build.

**Comment by probonopd** [comment]
Thank you. This fixes RPi2, but for RPi 1 we run into:

```
/home/runner/work/MiniDexed/MiniDexed/gcc-arm-10.3-2021.07-x86_64-arm-none-eabi/lib/gcc/arm-none-eabi/10.3.1/include/arm_neon.h:7175:1: error: inlining failed in call to 'always_inline' 'vcombine_f32': target specific option mismatch
 7175 | vcombine_f32 (float32x2_t __a, float32x2_t __b)
      | ^~~~~~~~~~~~
In file included from ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c:31:
../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c:489:5: note: called from here
  489 |     vst1q_f32(pState,vcombine_f32((vget_high_f32(Xn)),(Yn)));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../CMSIS_5/CMSIS/DSP/Include/arm_math_types.h:98,
                 from ../CMSIS_5/CMSIS/DSP/Include/dsp/filtering_functions.h:30,
                 from ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c:29,
                 from ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c:29:
/home/runner/work/MiniDexed/MiniDexed/gcc-arm-10.3-2021.07-x86_64-arm-none-eabi/lib/gcc/arm-none-eabi/10.3.1/include/arm_neon.h:7271:1: error: inlining failed in call to 'always_inline' 'vget_high_f32': target specific option mismatch
 7271 | vget_high_f32 (float32x4_t __a)
      | ^~~~~~~~~~~~~
In file included from ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c:31:
../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c:489:5: note: called from here
  489 |     vst1q_f32(pState,vcombine_f32((vget_high_f32(Xn)),(Yn)));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [../circle-stdlib/libs/circle/Rules.mk:140: ../CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.o] Error 1
Error: Process completed with exit code 2.
```

**Comment by probonopd** [comment]
Related?

https://github.com/kcat/openal-soft/pull/64

Do we need to build NEON code with `-mfpu=neon`?

**Comment by dcoredump** [comment]
I have added a check for __ARM_NEON inside Synth_Dexed so that the problem should not occure anymore for RPi1/RPi2. -DHAVE_NEON can be completely discarded.

**Comment by rsta2** [comment]
> Do we need to build NEON code with -mfpu=neon? How would one do that?

Builds for RPi 2-4 already use this option. The RPi 1 does not have a Neon FPU, so it cannot be specified there.

**Comment by dcoredump** [comment]
> > Do we need to build NEON code with -mfpu=neon? How would one do that?
> 
> Builds for RPi 2-4 already use this option. The RPi 1 does not have a Neon FPU, so it cannot be specified there.

I am not sure if we explicitly need this. My current tests for all for platforms seem to work and the NEON code is used without `-mfpu=neon` (on RPi3/4 CMSIS5-DSP-NEON and NEON code on RPi2 only CMCSIS5-DSP-NEON, RPi1 no NEON).

I would like to close this PR an create a new one so the CI can try to build hopefully completely.

**Comment by rsta2** [comment]
`-mfpu=neon` is enabled by default in the Circle build options for RPi 2-4:

https://github.com/rsta2/circle/blob/master/Rules.mk#L56

This has effect also for MiniDexed. For AArch64 the FPU does not need to enabled. This is done implicitly.

**Pull request closed without merging**
