### PR TITLE
Network + Arturia combined

### PR DESCRIPTION
**Pull request by probonopd**
This combines #743, #747.

We will still merge those individually, but we need to be sure that they will work together eventually.

### CODE REVIEW

**Comment by probonopd** [comment]
Note to self: Does not seem to work yet when combined. I get network but nothing on the screen of my emulated MiniLab 3 controller.

**Comment by probonopd** [comment]
I seem to be unable to resolve the merge conflicts. Maybe a GitHub thing.

**Comment by soyersoyer** [comment]
I think the problem is that it wants to resolve the conflicts in soyersoyer/dawdisplay, but that's in another PR also.

**Comment by probonopd** [comment]
OK, so probably we just need to get things merged one after the other?

**Comment by soyersoyer** [comment]
What if you checkout soyersoyer:dawdisplay to probonopd:arturia and then modify this PR to use your branch?

If the merge conflict is resolved in soyersoyer:dawdisplay, it will cause a lot of noise in the other PR.

**Comment by probonopd** [comment]
I don't have achieved that level of git wizardry quite yet ;-/

Nevermind, I'll probably just close this.

**Comment by omersiar** [comment]
IMHO maintainers should not change the code for the given branch for the PR, this creates a lot of conflicts. @probonopd if you want something to be changed or added/removed please kindly ask to the author, or course you can always  create a branch for the given PR.

**Pull request closed without merging**
