### PR TITLE
Only small changes for README.md, so images for RPi2/RPi3 can now created alsoOnly small fixes.

### PR DESCRIPTION
**Pull request by dcoredump**
Only small fixes. Everything works for me (includeing PR#41) for RPi2/RPi3/RPi4.

### CODE REVIEW

**Comment by probonopd** [comment]
This PR works for `pwm` on Raspberry Pi 2 but still breaks `hdmi`. Could not test with an i2s DAC due to the lack of hardware.

**Comment by dcoredump** [comment]
> This PR works for pwm on Raspberry Pi 2 but unfortunately still breaks hdmi. Could not test with an i2s DAC due to the lack of hardware. Did not test other Raspberry Pi models yet.

This is strange, because I only exchanged the sound generation which is the same for PWM and HDMI. I havn't touched the HDMI code.

Perhaps @rsta2 has an idea?

I will try the RPI2 builds with HDMI the next days. BTW: how can I enable HDMI or I2S?

**Comment by probonopd** [comment]
Thanks @rsta2. Perhaps some interrupt is taking too long (just a wild guess)?

> how can I enable HDMI or I2S?

In `minidexed.ini`, change `SoundDevice=pwm` to `SoundDevice=hdmi` or `SoundDevice=i2s`.

**Comment by rsta2** [comment]
> This is strange, because I only exchanged the sound generation which is the same for PWM and HDMI. I havn't touched the HDMI code.
>
> Perhaps @rsta2 has an idea?

No idea. But I don't have your new code here, to be able to look into it. The PR has been reverted. Perhaps we should work on a *develop* branch, so that versions, which not (fully) work do not need to be reverted. The *develop* branch can be merged to *main*, when the code is tested to work.

@smuehlst has done the circle-stdlib release now, and I want to create the PR for the multi-core support, which hopefully solves the USB problems on RPi 1-3. But I'm unsure, if I can branch off from current *main* at the moment. Will the PR from @dcoredump be merged soon or what will happen? @probonopd what to do?

BTW. I have seen a note, that the DSP code in CMSIS_5 is for Cortex-M only. @dcoredump  Are you sure, that it works with the Cortex-A and the earlier CPU of the RPi 1 too?

**Comment by probonopd** [comment]
> No idea. But I don't have your new code here, to be able to look into it.

It is actually contained in the new PR at https://github.com/probonopd/MiniDexed/pull/44.

> Perhaps we should work on a develop branch, so that versions, which not (fully) work do not need to be reverted.

Actually each PR is such a branch. I have added code that builds and uploads(!) each commit in each PR (those can be accessed via https://github.com/probonopd/MiniDexed/actions). So from now on we can test the built binaries without having to build locally or merge first.

**Comment by probonopd** [comment]
> Will the PR from @dcoredump be merged soon or what will happen? @probonopd what to do?

Once we can get it to work properly not only for PWM but also the other sound output methods and if no one objects, then I'd like to merge it because it removes the need for a forked Mini_Dexed (which was an interim "solution" anyway), and because I understand it is the basis for future effects.

**Comment by rsta2** [comment]
> It is actually contained in the new PR at https://github.com/probonopd/MiniDexed/pull/44.

I had a look into it. This only adds the *CMSIS_5* submodule and some object files in the *Makefile*. I can't talk about the changes in *Synth_Dexed*. I think that's @dcoredump 's field. Unfortunately I still have no idea, why HDMI does not work, because nothing has changed with it. I will test it with HDMI here.

> In the past I was quick to merge (and revert). With the above in place, I will be more careful with merging and test first.

OK.

> Unless you object to it @rsta2, in which case more discussion is needed.

No, I do not object. If @dcoredump wants to do it this way it's OK.

**Comment by rsta2** [comment]
I can reproduce the problem with HDMI. There is no problem with I2S and with the version from *probonopd/MiniDexed/main*. I will look for the reason tomorrow.

**Comment by rsta2** [comment]
Already found the problem. @dcoredump please apply the following patch to your project:

```
diff --git a/src/dexed.cpp b/src/dexed.cpp
index 4d77d40..be43a27 100644
--- a/src/dexed.cpp
+++ b/src/dexed.cpp
@@ -214,7 +214,7 @@ void Dexed::getSamples(uint16_t n_samples, int16_t* buffer)
 #endif
 
   //arm_scale_f32(sumbuf, 0.00015, sumbuf, AUDIO_BLOCK_SAMPLES);
-  arm_float_to_q15(sumbuf, buffer, AUDIO_BLOCK_SAMPLES);
+  arm_float_to_q15(sumbuf, buffer, n_samples);
 }
 
```

Then it will work with HDMI too. Another hint: If you want to define a C-macro in the *Makefile*, you should use `DEFINE += -DARM_MATH_NEON`. `CXXFLAGS=` will not work.

**Comment by probonopd** [comment]
@dcoredump please ping me once you have applied this to [Synth_Dexed](https://codeberg.org/dcoredump/Synth_Dexed), then I can retrigger the build here.

**Comment by probonopd** [comment]
Thanks @rsta2. It works for me :+1: 

I am merging this now but once @dcoredump updates Synth_Dexed we can remove https://github.com/probonopd/MiniDexed/pull/44/commits/71c5c55aa88e5d7532e1eb4f515f3037befc4fee.

**Comment by dcoredump** [comment]
> BTW. I have seen a note, that the DSP code in CMSIS_5 is for Cortex-M only. @dcoredump Are you sure, that it works with the Cortex-A and the earlier CPU of the RPi 1 too?

Yes, thanks for the hint. But the DSP functions are also for other processors. Those functions are really helpful and some optimizations of the CPU (like NEON) can be used.

**Comment by dcoredump** [comment]
> Already found the problem. @dcoredump please apply the following patch to your project:

Uumpf. Damn! Copy&paste and not changed the parameters... Thanks @rsta2!

It's now fixed in upstream.

**Comment by rsta2** [comment]
@probonopd The most recent commit of Synth_Dexed is not yet selected in the submodule reference in MiniDexed.

**Comment by probonopd** [comment]
Thanks @dcoredump and @rsta2, updated.

**Pull request merged**
