### PR TITLE
Implement MIDI CC 120 (All Sound Off) and 123 (All Notes Off)

### PR DESCRIPTION
**Pull request by probonopd**
Closes https://github.com/probonopd/MiniDexed/issues/126

### CODE REVIEW

**Comment by probonopd** [comment]
Turns out it wasn't as easy as that...

```
mididevice.cpp: In member function 'void CMIDIDevice::MIDIMessageHandler(const u8*, size_t, unsigned int)':
mididevice.cpp:201:22: error: 'class CMiniDexed' has no member named 'panic'
  201 |      m_pSynthesizer->panic (pMessage[2], nTG);
      |                      ^~~~~
mididevice.cpp:205:22: error: 'class CMiniDexed' has no member named 'notesOff'
  205 |      m_pSynthesizer->notesOff (pMessage[2], nTG);
      |                      ^~~~~~~~
make: *** [../circle-stdlib/libs/circle/Rules.mk:144: mididevice.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by probonopd** [comment]
@diysynth can you please test the build from https://github.com/probonopd/MiniDexed/suites/6197459086/artifacts/218456185 and report back whether it works for you as intended?

Thanks!

**Comment by probonopd** [comment]
@rsta2 looks about right?

**Comment by rsta2** [comment]
Yes.

**Pull request merged**
