### PR TITLE
Automatic bank jumping from voice menu

### PR DESCRIPTION
**Pull request by arsamus**
Hi everybody, this PR allows to jump to the next or previous Bank from Voice menu when move beyond the last (32) or the first (1) voice in a continues way. This avoid to go back and forth between Voice and Bank menus when exploring different patches.

This solve #338 posted by @diyelectromusic

### CODE REVIEW

**Comment by probonopd** [comment]
This seems to work when using buttons to change voices, but seems not to work when using MIDI CCs to change voices. For example, MIDI controllers like the M-AUDIO Keyststation Mini 32 NK3 can be set up so that its + and - keys change voices. This presents somewhat of a dilemma: The CCs don't say "increase/decrease voice", but they send particular voice numbers. So the question is whether we want to do some trickery to interpret e.g., voice 32/"33" on bank 0/"1" as voice 0/"1" on bank 1/"2", and so on... Wdyt?

**Comment by arsamus** [comment]
> The CCs don't say "increase/decrease voice", but they send particular voice numbers. So the question is whether we want to do some trickery to interpret e.g., voice 32/"33" on bank 0/"1" as voice 0/"1" on bank 1/"2", and so on... Wdyt?

Hi @probonopd, yes that is an issue. I've noticed that Program Change signal just send a value between 0 and 127 instead an up or down order. There are a posible solution. It is posible to modify "programchange" method on Minidexed class that instead of set the value sent by the midi controller, jump up one position if the value is increased or jump down one in case the value is decresed. When voice gets the upper value (>32), jump to the next bank and when get 0 jump to the previous one. In this case the controller acts as a "rotary encoder". 

In my synth when you hit "PROG-UP" and the voice number is 127, the counter goes to 0, and when hit "PROG-DOWN" on 0, the counter goes to 127, so the solution may work. I don't if all controllers have the same comportamnt. 

What do you think?

**Comment by probonopd** [comment]
I think it might be worth a try... if it doesn't overly complicate the code and makes it unmaintainable. Maybe it should be possible to disable the behavior?

**Comment by arsamus** [comment]
Ok. Let's try. All feature could be optionally activated via minidexed.ini.

**Comment by arsamus** [comment]
I've just added a Minidexed.ini variable "AutoBankSkip" that switch between original Voice and Bank behavior and Auto Bank jumping behavior.  With this user can choose and set it preferred feature.

**Comment by probonopd** [comment]
If I am not mistaken, then https://github.com/probonopd/MiniDexed/commit/4a8241226d31c749b9e7aee2a2fae0096dd06741 is implementing this as well. Hence closing here. (No particular reason why I merged the other PR instead of this one, so no offense intended.) Thanks @arsamus .

**Pull request closed without merging**
