### PR TITLE
SSD1306 display rotation support and fix for #421

### PR DESCRIPTION
**Pull request by diyelectromusic**
Fix for Issue #421 - circle sound drivers have moved to their own subdirectory and library.

### CODE REVIEW

**Comment by diyelectromusic** [comment]
This will need the latest develop branch of circle of course...

**Comment by probonopd** [comment]
```
circle_stdlib_app.h: In member function 'virtual bool CStdlibAppStdio::Initialize()':
circle_stdlib_app.h:218:33: error: invalid initialization of reference of type 'CConsole&' from expression of type 'FATFS'
  218 |                 CGlueStdioInit (mFileSystem, mConsole);
      |                                 ^~~~~~~~~~~
```

**Comment by probonopd** [comment]
```
In file included from kernel.h:23,
                 from kernel.cpp:20:
circle_stdlib_app.h: In member function 'virtual bool CStdlibAppStdio::Initialize()':
circle_stdlib_app.h:218:33: error: invalid initialization of reference of type 'CConsole&' from expression of type 'FATFS'
  218 |                 CGlueStdioInit (mFileSystem, mConsole);
      |                                 ^~~~~~~~~~~
```

**Comment by probonopd** [comment]
It built :+1: 

Let's test it:
[MiniDexed_2023-01-20-d0b139c](https://github.com/probonopd/MiniDexed/suites/10495115589/artifacts/520539396)

**Comment by diyelectromusic** [comment]
I get an assertion failing in circle-stdlib/libs/circle-newlib/libgloss/circle/io.cpp(687): circle_fat_fs

There was a corresponding update to newlib as well as stdlib so are you using the develop version of that too?

**Comment by diyelectromusic** [comment]
Yep, looks like we need this too: https://github.com/smuehlst/circle-newlib/commit/48bf91d4602756116eb407f0177015d5ece0b805

**Comment by probonopd** [comment]
https://github.com/probonopd/MiniDexed/pull/422/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R23-R30 shows the changes I have made; do I need to make further changes?

**Comment by diyelectromusic** [comment]
I believe it is one of the sub-modules for circle_stdlib, alongside circle itself...?

**Comment by diyelectromusic** [comment]
Yes, so in the build.yml I guess we need to add something to also checkout the develop branch of newlib alongside circle (after checking out the develop branch of circle-stdlib itself)?

**Comment by probonopd** [comment]
Indeed. Submodules are pulling in other submodules.

**Comment by probonopd** [comment]
@diyelectromusic how does [MiniDexed_2023-01-21-63fac3c](https://github.com/probonopd/MiniDexed/suites/10502991436/artifacts/521205226) look?

**Comment by probonopd** [comment]
Reminder to self, also need to add descriptions for

```
SSD1306LCDRotate=0
SSD1306LCDMirror=0
```

to the wiki.

**Comment by diyelectromusic** [comment]
That seems to have done the trick! :)

Phew, that was a lot more complicated than it should have been!!

Kevin

**Comment by diyelectromusic** [comment]
> @diyelectromusic which values are allowed for these, just 0 and 1?

Actually 0 and <>0 - I think that is the same as other boolean values in the config file...

**Comment by probonopd** [comment]
OK, for simplicty let's document it as 0/1 then.

Thanks a lot for your help!

**Comment by vujnovich** [comment]
So is the setting in the ini file to toggle the flip? I hadn't downloaded
it and checked . I'll give it a go a bit later. Again. Thanks for the work
you put into this project

**Comment by probonopd** [comment]
Yes, please try it out and let us know whether it works for you. Thanks!

**Comment by Banana71** [comment]
Moin, 

You've done a lot of good there :-)
SSD1306LCDRotate & SSD1306LCDMirror work perfectly.
But why does the mirror effect work over the short axis? I would have expected mirroring over the long axis, similar to a head-up display in a car. 
All other functions on the MiniDexed work as usual.

**Comment by diyelectromusic** [comment]
> But why does the mirror effect work over the short axis?

As the starting point was MT32-Pi I just ported over the two modes it already uses.  I had a quick look at the ssd1306 datasheet, but haven't fully decoded the registers to know if there are additional feasible modes.  But now it all looks up and running I might take a look again at some point...

Kevin

**Comment by probonopd** [comment]
We should test and put this into the documentation. Is the following correct?

* To rotate the display by 180 degrees, set `SSD1306LCDRotate=1`
* To mirror the display along the short axis, set `SSD1306LCDMirror=1`
* To mirror the display along the long axis, set `SSD1306LCDMirror=1` and `SSD1306LCDRotate=1`

**Comment by diyelectromusic** [comment]
> We should test and put this into the documentation. Is the following correct?

I think we're saying:
* To rotate the display by 180 degrees, set `SSD1306LCDRotate=1`
* To mirror the display set `SSD1306LCDMirror=1`

Note that a mirrored display will be the same orientation when viewed mirrored via the short axis, but upside down when viewed mirrored via the long axis.  For a "heads up display" style effect it would need to be both mirrored and rotated.

**Comment by Banana71** [comment]
Haha, 
with 2 bits you can represent 4 possibilities.
Now everything is clear, it was still very early in the morning when I tried it out.
Good that we talked about it, all ambiguities have been eliminated :-D

**Comment by probonopd** [comment]
Also added to documentation.

**Comment by diyelectromusic** [comment]
We've made it!  Hurrah! :)

**Comment by vujnovich** [comment]
So I just had the time to try the new build. Looking at the config, I
noticed the lcd mirror option is in the ssd1306 , not the hd44780. Bah, I'm
gonna try it anyway 😜. Suppose I didn't mention I was using the hd44780
with a backpack. Anyway cheers

**Comment by diyelectromusic** [comment]
> So I just had the time to try the new build. Looking at the config, I noticed the lcd mirror option is in the ssd1306 , not the hd44780. Bah, I'm gonna try it anyway 😜. Suppose I didn't mention I was using the hd44780 with a backpack. Anyway cheers

I thought you'd said you'd tried it with MT32-Pi and wondered if we could do the same. MT32-Pi can only rotate a SSD1306 based display too (well, actually it might support other "graphical" displays, but ssd1306 is the only one we do too).

The hd44780 is not a "graphical" display and support in MT32-Pi can't rotate either, so I didn't bother even looking...

Kevin

**Pull request merged**
