### PR TITLE
Fix for Issue #369 to correctly recognise ChannelsSwapped config setting

### PR DESCRIPTION
**Pull request by diyelectromusic**
Suggested fix for Issue #369

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @diyelectromusic. Can someone affected by the issue please test [MiniDexed_2022-12-01-fc04648](https://github.com/probonopd/MiniDexed/suites/9617837133/artifacts/459169484) and let us know here whether it fixes the issue?

**Comment by mongio** [comment]
the channelsswapped now works after the fix :-) in my system (RPi4 with the purple PCM5102 DAC). Have to swap channels to 1 to get the left and right on the correct positioning. Well done 👍 please insert the fix into the official builds:-)

**Comment by mongio** [comment]
is the fix included in last build? It seems inverted again to me.

**Comment by diyelectromusic** [comment]
Is this one still outstanding?  Do I need to do anything?

**Comment by probonopd** [comment]
Thank you very much @diyelectromusic

**Pull request merged**
